version: '3'

services:
  web:
    build: .
    container_name: pillulu-web
    restart: always
  nginx:
    image: nginx:latest
    container_name: pillulu-nginx
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl
    depends_on:
      - web
    restart: always

